repos:
- repo: local
  hooks:
    - id: run-pre-commit
      name: run-pre-commit
      entry: ./pre-commit.sh
      language: script
      pass_filenames: false
      require_serial: true
      types_or: [python]